name: Cypress

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: yarn
    - name: Build
      run: yarn build
    - name: Cypress
      run: yarn cy:ci
